apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: basic-cluster
  region: eu-north-1

nodeGroups:
  - name: ng-1
    instanceType: m5.large
    desiredCapacity: 10

  - name: ng-2
    instanceType: m5.xlarge
    desiredCapacity: 2

  - name: ng-3
    instanceType: m5.xlarge
    desiredCapacity: 5
